- name: disable nodejs commands
  ansible.builtin.command: dnf module disable nodejs -y
- name: enable nodejs commands
  ansible.builtin.command: dnf module enable nodejs:20 -y
- name: install nodejs
  ansible.builtin.package:
    name: nodejs
    state: present
- name: add expense user
  ansible.builtin.user:
    name: expense
    comment: add expense system user
    system: true
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /app
    state: absent


- name: creating app directory
  ansible.builtin.file:
    state: directory
    path: /app

- name: Download the expense application
  ansible.builtin.get_url:
    url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
    dest: /tmp/backend.zip

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: /tmp/backend.zip
    dest: /app
    remote_src: yes

- name: Install dependencies 
  community.general.npm:
    path: /app

- name: Copy backend service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: install mysql
  ansible.builtin.package:
    name: mysql
    state: present

- name: Install PyMySQL on backend
  ansible.builtin.package:
    name: python3-PyMySQL
    state: present

- name: Import expense db
  community.mysql.mysql_db:
    login_user: root
    login_password: ExpenseApp@1
    name: expense
    state: present
    target: /app/schema/backend.sql
    login_host: "mysql.msdevsecops.fun"

- name: start and Enable backend
  ansible.builtin.systemd_service:
    name: backend
    state: started
    daemon_reload: true
    enabled: true