- name: install mysql
  ansible.builtin.package:
    name: mysql-server
    state: present

- name: start and enable mysql
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: true

- name: setup root password
  ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
